### ISSUE TITLE
Scaling the browser window reveals the native scrollbars in chrome

### ISSUE THREAD

**Issue by fpauser** [yairEO/fakescroll#14]
When scaling the browser window native scrollbars appear in addition to the fakescroll scrollbars:

![image](https://user-images.githubusercontent.com/7302/51309476-c9f6be00-1a44-11e9-8839-be8da31886ce.png)

This happens in the latest stable google chrome.

**Comment by mohmedxpmpa** [comment]
me too

**Comment by fpauser** [comment]
I switched over to [SimpleBar](https://github.com/Grsmto/simplebar). Its also lightweight and actively maintained.

**Comment by yairEO** [comment]
I have nothing to maintain because there were no issues and I wrote it years ago and it's so simple and small it just works great. 

If you care specifically about people who scale their browser than simply adjust your CSS accordingly. 

In terms of javascript, there can be nothing lighter and better than this script (and all my other scripts for the matter)

**Comment by yairEO** [comment]
@fpauser - looking at SimpleBar NPM it's `504 kB` where mine is `65.1 kB` (I can get it down a lot more, it's including minified + unfinished code which is a duplication, so I honestly do not understand you claim for it to be "lightweight". it's literally close to **8 times** my code.

**Comment by ataylor32** [comment]
I haven't seen this issue occur myself, but if it is still a problem, I wonder if [disabling native scrollbars](https://jsfiddle.net/c2gtn3d1/) would fix the problem.
